#!/bin/sh

ARMASM="armasm -g --debug --apcs /interwork --keep --cpu=ARM968E-S" #TODO Remove debug flags for final build
ARMCC="armcc -c -W --debug --apcs /interwork --debug --cpu=ARM968E-S -O0"
ARMLINK="armlink --list=system-rom.lst --map --symbols --scatter=../build/embedded_scat.scat --entry=0"

#--libpath=/home/amulinks/spinnaker/tools/RVDS40/RVCT/Data/4.0/400/lib

cd ../src

$ARMASM embed_uish.s
$ARMASM pl340.s
$ARMASM processor.s
$ARMASM ram_test.s
$ARMASM start.s
$ARMASM vectors.s

$ARMCC dma.c
$ARMCC eth_link.c
$ARMCC flood_fill.c
$ARMCC globals.c
$ARMCC interrupt_service_routines.c
$ARMCC peripheral_inits.c
$ARMCC phy.c
$ARMCC main.c
$ARMCC reg_test.c

OBJS="	dma.o \
		embed_uish.o \
		eth_link.o \
		flood_fill.o \
		interrupt_service_routines.o \
		globals.o \
		peripheral_inits.o \
		phy.o \
		pl340.o \
		processor.o \
		ram_test.o \
		reg_test.o \
		main.o \
		start.o \
		vectors.o"

$ARMLINK --output system-rom.elf $OBJS

rm *.o

mv system-rom.elf ../bin
mv system-rom.lst ../bin

cd ..

fromelf --bin --output bin/system-rom.bin bin/system-rom.elf
fromelf -c bin/system-rom.elf > build/fromelf
